//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Engine
    {
        public System.Guid EngineId { get; set; }
        public string VehicleType { get; set; }
        public string VehicleBrand { get; set; }
        public string VehicleModel { get; set; }
        public string EngineType { get; set; }
        public string EnginePrice { get; set; }
    }
}
