//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleManagementSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VehicleMSysEntities : DbContext
    {
        public VehicleMSysEntities()
            : base("name=VehicleMSysEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bike> Bikes { get; set; }
        public virtual DbSet<BikeComponentList> BikeComponentLists { get; set; }
        public virtual DbSet<Bus> Buses { get; set; }
        public virtual DbSet<BusComponentList> BusComponentLists { get; set; }
        public virtual DbSet<Car> Cars { get; set; }
        public virtual DbSet<CarComponentList> CarComponentLists { get; set; }
        public virtual DbSet<Component> Components { get; set; }
  
        public virtual DbSet<VehicleComponentList> VehicleComponentLists { get; set; }
        public virtual DbSet<Vehicles> Vehicles1 { get; set; }

        //      public virtual DbSet<Engine> Engines { get; set; }
    }
}
