//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleComponentList
    {
        public int ComponentListID { get; set; }
        public System.Guid VehicleGUID { get; set; }
        public int ComponentID { get; set; }
    
        public virtual Component Component { get; set; }
        public virtual Vehicles Vehicle { get; set; }
    }

    public partial class CopyOfVehicleComponentList
    {
        public int ComponentListID { get; set; }
        public System.Guid VehicleGUID { get; set; }
        public int ComponentID { get; set; }

        public virtual Component Component { get; set; }
        public virtual Vehicles Vehicle { get; set; }
    }
}
